# Pair Numpy

#### **Creación y Indexación:**

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.


In [ ]:
import numpy as np

array1D = np.random.randint(10,100, size=(50))

array1D[::5]


array([39, 98, 73, 67, 31, 53, 72, 66, 31, 54], dtype=int32)

2. Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.


In [9]:
array1D = np.random.randint(1,21, size=(30))

array1D[1::2]

array([ 9, 18, 12, 13, 15, 16,  7,  5, 18,  5,  2, 19, 14, 17, 11],
      dtype=int32)

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.


In [19]:
array2D = np.random.uniform(0, 100, (4,6))

np.round(array2D[-1,:], 2)

array([96.4 , 24.08, 41.02, 14.65, 43.68, 72.14])

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [22]:
array3D = np.round(np.random.sample(size = (2,3,5)),1)
array3D

array([[[0.5, 0.3, 0.8, 0.1, 0.9],
        [0.6, 0.4, 0.5, 0.8, 0.1],
        [0.1, 0.4, 0.1, 1. , 0. ]],

       [[0.9, 0.5, 0.5, 0.9, 0.3],
        [0.9, 0.3, 0.9, 0.2, 0.5],
        [0.7, 0.1, 0.1, 0.5, 0.8]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
   * Si el valor del array es igual que la media, se reemplaza por "A".
   * Si el valor del array es mayor que la media, se reemplaza por "B".
   * Si el valor del array es menor que la media, se reemplaza por "C".
   * Si el valor es igual que el máximo, se reemplaza por "D".
   * Si el valor es igual que el mínimo, se reemplaza por "E".

     ```python
     # a modo de ejemplo. Si tenemos el siguiente array
     [[[0.4, 0.7, 0.2, 0.9, 0.2],
         [0.1, 0.9, 0.6, 0.1, 0.2],
         [1. , 0.2, 0.1, 0.8, 0.3]],

     [[0. , 0.3, 0.4, 0.5, 0.1],
         [0.5, 0.7, 0.9, 0. , 0.8],
         [0.5, 0.3, 0.5, 0.8, 0.1]]])

     # sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

     # nuestro array vacío debería quedar como este: 
     [[["A", "B", "C", "B", "C"],
         ["C", "B", "B", "C", "C"],
         ["D" , "C", "C", "B", "C"]],

     [["E" , "C", "A", "B", "C"],
         ["B", "B","B", "E" , "B"],
         ["B", "C", "B", "B", "C"]]])
     ```


In [48]:
array_vacio_3D= np.empty((2,3,5),dtype = str)
array_vacio_3D

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [36]:
media_array = np.mean([array3D])

In [37]:
media_array

np.float64(0.49)

In [49]:
array_vacio_3D[array3D == media_array] = "A"
array_vacio_3D[array3D > media_array] = "B"
array_vacio_3D[array3D < media_array] = "C"
array_vacio_3D[array3D == np.max(array3D)] = "D"
array_vacio_3D[array3D == np.min(array3D)] = "E"



In [50]:
array3D

array([[[0.5, 0.3, 0.8, 0.1, 0.9],
        [0.6, 0.4, 0.5, 0.8, 0.1],
        [0.1, 0.4, 0.1, 1. , 0. ]],

       [[0.9, 0.5, 0.5, 0.9, 0.3],
        [0.9, 0.3, 0.9, 0.2, 0.5],
        [0.7, 0.1, 0.1, 0.5, 0.8]]])

In [51]:
array_vacio_3D

array([[['B', 'C', 'B', 'C', 'B'],
        ['B', 'C', 'B', 'B', 'C'],
        ['C', 'C', 'C', 'D', 'E']],

       [['B', 'B', 'B', 'B', 'C'],
        ['B', 'C', 'B', 'C', 'B'],
        ['B', 'C', 'C', 'B', 'B']]], dtype='<U1')


#### Si te queda tiempo, puedes hacer los siguientes ejercicios:

1. Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.


In [53]:
array3D_int = np.random.randint(0,101, size=(30)).reshape(2,3,5)

array3D_int

array([[[53, 35,  3, 72, 86],
        [12, 40, 69, 27, 10],
        [85, 31, 18, 46, 25]],

       [[80, 49, 48, 18, 53],
        [22, 86, 10, 52, 26],
        [94, 25, 26, 29, 39]]], dtype=int32)

2. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.


3. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.


4. Utiliza el array 3D del ejercicio anterior de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).


5. Utiliza el array 3D del ejercicio anterior 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).
